### ISSUE TITLE
Проблема с точкой с запятой #6 - ESLint

### ISSUE THREAD

**Issue by trofivan** [usulpro/js-stack-from-scratch#10]
### Type of issue: (feature suggestion, bug, translation?)
Проблема с gulp-eslint

### Chapter:
6 - ESLint

### If it's a bug:

Когда использую конструкцию вида:
```
gulp.task('lint', () =>
  gulp.src([paths.allSrcJs, paths.gulpFile])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError())
);
```
Линтер ругается на то, что после .pipe(eslint.failAfterError()) нету ";"
Как объяснить линтеру, что данный код валиден и ; там не нужна?
Когда ставлю ; - не может скомпилировать.
Когда переношу последнюю скобку на строку выше, то не ругается, но такая разметка кода выглядит совсем нелепо и не логично:
```
gulp.task('lint', () =>
  gulp.src([paths.allSrcJs, paths.gulpFile])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError()));
```

**Comment by usulpro** [comment]
@trofivan 
верно, эта проблема появилась после выхода  версии `"eslint-config-airbnb": "^13.0.0"`
данный вопрос [поднят](https://github.com/verekia/js-stack-from-scratch/issues/90) в англоязычной версии а так же обсуждается в самом [ESLint](https://github.com/eslint/eslint/issues/7588)
Пока проблема не решена, можно сделать следующее:

1. Отключить это правило локально для данного файла:
`/* eslint-disable import/no-extraneous-dependencies, comma-dangle, no-console */` - в начале файла

2. Вернуть 12ю версию "eslint-config-airbnb":
`npm i eslint-config-airbnb@^12.0.0 --save-dev`
или просто скопируйте себе package.json из данной главы и `npm i`

**Comment by trofivan** [comment]
@UsulPro `/* eslint-disable import/no-extraneous-dependencies, comma-dangle, no-console */` не совсем хорошее решение, лучше временно оставить закрытие скобки на предыдущей строке. Спасибо.

**Comment by usulpro** [comment]
> Should not be an issue anymore with the new release of the tutorial.
