### ISSUE TITLE
Обновление пакета color на втором шаге

### ISSUE THREAD

**Issue by Sherevv** [usulpro/js-stack-from-scratch#11]
В разделе "2 - Installing and using a package" используется пакет color. При установке на данный момент командой `yarn add color` ставится версия 1.0.3, в зависимостях автора  - 0.11.3.
В общем, в новой версии пакета нет функции `hexString()` (есть функция `hex`), как в примере, соответственно, отваливается с ошибкой.

UPD. В репозитории автора это исправлено.

**Comment by usulpro** [comment]
Спасибо за замечание!

Обновил Русскую версию. Полагаю, теперь можно закрыть.
