### ISSUE TITLE
Пропал перевод 1 версии

### ISSUE THREAD

**Issue by meam364** [usulpro/js-stack-from-scratch#18]
Пропал перевод 1 версии после мержа. Последняя рабочая версия https://github.com/UsulPro/js-stack-from-scratch/tree/7e487c7ee9e3738ef58eabf4dfad9cbcbf6c77cd . Разделите на 2 ветки, чтобы была возможность читать уже переведенный туториал

**Comment by usulpro** [comment]
Иван, перевод первой части теперь [здесь](https://github.com/UsulPro/js-stack-from-scratch-v1-rus)
