### ISSUE TITLE
Прошу учесть

### ISSUE THREAD

**Issue by leonidkuznetsov18** [usulpro/js-stack-from-scratch#9]
1 - Не всегда указано в каких директориях создавать тот или иной файл(особенно это видно в начале)
2 - Было бы здорово что б изначально включалась обработка на локальном сервере, потому что открытие файла index.html с папки dist уже как то дико и у меня к примеру не отрабатывает 
http://take.ms/h96wE, он его просто не генерирует
3 - Откажитесь от Gulp , через чур громоздким и запутанным в дальнейшем на мое мнение получиться приложение.
4 - Продолжайте в том же духе!!!

**Comment by usulpro** [comment]
@MrChe, спасибо за отзыв!
Мы начинаем перевод второй части руководства, значительно переработанной по сравнению с первой.
